# Generated by Django 6.0.1 on 2026-01-21 12:21

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_team_employee_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 400, 'width': 400}}, verbose_name='Image'),
        ),
    ]
